language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=packaging
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=coverage
    - python: 3.6
      env: TOXENV=flake8

branches:
  only:
    - master

before_install:
  - echo $TRAVIS_PYTHON_VERSION

install:
  - pip install tox-travis
  - pip install coverage
  - pip install coveralls
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version


script:
  - tox
  - pytest tests/ --cov=pyDataverse --cov-report=term-missing --cov-report=xml --cov-report=html

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - stefan.kasberger@univie.ac.at
    on_success: change
