language: python
cache: pip
dist: xenial

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: pypy
      env: TOXENV=pypy
    - env: TOXENV=flake8

before_install:
  - python --version


install:
  - pip install tox-travis
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

script:
  - tox

after_success:
  - pip install codecov
  - coveralls

notifications:
  email:
    recipients:
      - stefan.kasberger@univie.ac.at
    on_success: never
    on_failure: always
